server:
  port: 8082
spring:
  application:
    name: tanhua-dubbo-db
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tanhua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    password: root
    username: root
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.tanhua.dubbo.api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id